CityProject/__pycache__/website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    username = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())

CityProject/__pycache__/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "helloworld"
    app.config['SQL_ALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    from .models import User

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not path.exists("website/" + DB_NAME):
        db.create_all(app=app)
        print("Created database!")

CityProject/__pycache__/website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from . import db
from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in!", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Password is incorrect.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html")


@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get("email")
        username = request.form.get("username")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()

        if email_exists:
            flash('Email is already in use.', category='error')
        elif username_exists:
            flash('Username is already in use.', category='error')
        elif password1 != password2:
            flash('Password don\'t match!', category='error')
        elif len(username) < 2:
            flash('Username is too short.', category='error')
        elif len(password1) < 6:
            flash('Password is too short.', category='error')
        elif len(email) < 4:
            flash("Email is invalid.", category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('User created!')
            return redirect(url_for('views.home'))

    return render_template("signup.html")


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))

CityProject/__pycache__/website/views.py
from flask import Blueprint, render_template,request
import requests
import json 
from flask_login import login_required,current_user
views = Blueprint("views", __name__)



@views.route('/')
@login_required  
def home():  
    return render_template('index.html');  
    

        
@views.route('/palestine City/Jerusalem')  
def AlAqsaMosque():  
    return render_template('AlAqsaMosque.html')

@views.route('/palestine City/jericho')  
def jericho():  
    return render_template('jericho.html')

@views.route('/palestine City/Gaza')  
def gaza():  
    return render_template('gaza.html')

@views.route('/palestine City/safed')  
def safed():  
    return render_template('safed.html')

@views.route('/palestine City/yafa')  
def yafa():  
    return render_template('yafa.html')

@views.route('/{city_name}/weather')
def weather():
    return render_template('weather.html')


def get_weather_data(city_name):
    raw_data = requests.get(
        f'https://api.openweathermap.org/data/2.5/weather?q={city_name}&appid=bc368fbffb0d27697c1822903f154f03')
    return raw_data.json()
 

@views.route('/city', methods=['POST'])
def city():
    name = request.form['city_name']
    data = get_weather_data(name)
    
    weather_main = data['weather'][0]['main']
    weather_description = data['weather'][0]['description']
    temp = data['main']['temp']
    c_temp = format(float(float(temp) - 273.15), '.2f')
    pressure = data['main']['pressure']
    humidity = data['main']['humidity']
    return render_template('city.html', city_name=name, weather=weather_main,
                           weather_description=weather_description, temperature=c_temp,
                           pressure=pressure, humidity=humidity)    

@views.route('/AddCity')  
def addCity():
    render_template('add_city.html')                         

CityProject/__pycache__/website/templates/AlAqsaMosque.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Template Main CSS File -->
  
    <title>Jerusalem City</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
  
    <!-- Favicons -->
    <link href="website/static/assets/img/favicon.png" rel="icon">
    <link href="website/static/assets/img/apple-touch-icon.png" rel="apple-touch-icon">
  
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  
    <!-- Vendor CSS Files -->
    <link href="static/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="static/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="static/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  
    <!-- Template Main CSS File -->
    <link href="/website/" rel="stylesheet">

</head>
<body style="background-color:slategrey;">
    <h1>Jerusalem City</h1>
     <img src="{{url_for('static', filename='assets/img/slide/slide_1.jpg')}}" style="display: block;
     margin-left: auto;
     margin-right: auto;
     width: 50%;"  />

        <p style="font-size: 25px;">Al-Quds (Hebrew: יְרוּשָׁלַיִם Yerushalayim) is the largest city in occupied historical Palestine in terms ,<br>
            of area and population, and the most important religiously and economically. It is known by other names <br>
            in the Arabic language, such as: Bait Al-Maqdis, Al-Quds Al-Sharif, the first of the two Qiblas, and in <br>
            the Bible as Jerusalem, and Israel officially calls it: Jerusalem Al-Quds. <br><br><br>

            Arabs, Palestinians, and a wide range of supporters of the Palestinian cause consider it the capital of <br>
            the future state of Palestine after liberation, as stated in the document of the Palestinian Declaration <br>
            of Independence that took place in Algeria on November 15, 1988 AD, (As for historically, their Jebusite <br>
            ancestors were the first to build and inhabit the city in the fifth millennium BC). While Israel considers<br>
            it its unified capital, after annexing the eastern part of the city in 1980 AD, which it occupied after <br>
            the 1967 war (the Jews consider it their religious and national capital for more than 3000 years). As for <br>
            the United Nations and the international community, it does not recognize Jerusalem as the capital of Israel,<br>
            considers East Jerusalem part of the Palestinian territories, and does not recognize its annexation to the Hebrew <br>
            state, with some exceptions. Jerusalem is located within the Hebron mountain range and mediates the area between<br> 
            the Mediterranean Sea and the northern end of the Dead Sea. This city has grown and expanded its borders much more<br> 
            than it was in previous eras.<br>
        </p> 
        <div class="previous"  style="background-color: #919292;
  top:80px;
  color: white;
  align-items: right;
  font-size: 25px;
  margin-left: 70%;
  margin: 10 px;
  padding: 10px;
  position:center;
  right:60%;
  float: right;">
            <a href="{{ url_for('views.home') }}">Retun </a>
            </div>   
    </div>   
</body>
</html>

CityProject/__pycache__/website/templates/add_city.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add City</title>
</head>
<body>
    <h1 align="center">Add City</h1>
    
    <form method="POST">
        <input type="file" name="file" />  
        <input type = "submit" value="Upload"> 
      <textarea name="text" id="text" class="form-control"></textarea>
      <br />
      <div align="center">
        <button type="submit" class="btn btn-lg btn-primary">Add Ciy</button>
      </div>
    </form>
    <br />
    <div align="center">
      <a href="/index"
        ><button type="button" class="btn btn-lg btn-secondary">Back</button></a
      >
    </div>
</body>
</html>
   

CityProject/__pycache__/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body style="background-color:slategrey">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
           
            <a class="nav-item nav-link" href="/login">Login</a>
            <a class="nav-item nav-link" href="/sign-up">Sign Up</a>
          </div>
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        {% for category, message in messages %}
        {% if category == "error" %}
        <div class="alert alert-danger alter-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% endif %}

        {% endfor %}
      {% endif %}
    {% endwith %}
    <div class="container">{% block content %}{% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

CityProject/__pycache__/website/templates/city.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <title>{{ city_name }} Weather</title>
</head>

<body style="background-color:slategrey;">
    <div class="table-title">
        <h3>{{city_name}} Weather</h3>
    </div>
    <table class="table-fill">
        <thead>
            <tr>
                <th class="text-left">Measurement</th>
                <th class="text-left">Value</th>
            </tr>
        </thead>
        <tbody class="table-hover">
            
            <tr>
                <td class="text-left">Weather</td>
                <td class="text-left">{{weather}}</td>
            </tr>
            <tr>
                <td class="text-left">Weather Description</td>
                <td class="text-left">{{weather_description}}</td>
            </tr>
            <tr>
                <td class="text-left">Temperature</td>
                <td class="text-left">{{temperature}}°C</td>
            </tr>
            <tr>
                <td class="text-left">Pressure</td>
                <td class="text-left">{{pressure}}</td>
            </tr>
            <tr>
                <td class="text-left">Humidity</td>
                <td class="text-left">{{humidity}}</td>
            </tr>
        </tbody>
    </table>

    <div class="previous"  style="background-color:  #919292;
    top:80px;
    color: white;
    align-items: right;
    font-size: 25px;
    margin-left: 70%;
    margin: 10 px;
    padding: 10px;
    position:center;
    right:60%;
    float: right;">
              <a href="{{ url_for('views.weather') }}">Retun </a>
              </div>

              <div class="next" style="background-color:  #919292;
              top:90px;
              color: white;
              align-items: right;
              font-size: 25px;
              margin-left: 70%;
              margin: 10 px;
              padding: 10px;
              position:center;
              right:60%;
              float: top;" >
              <a href="{{ url_for('views.home') }}">Home Page </a>
              </div>
</body>

</html>

CityProject/__pycache__/website/templates/gaza.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gaza City</title>
</head>
<body style="background-color:slategrey;">
    <h1>Gaza City</h1>
    
        <img src="{{url_for('static', filename='assets/img/slide/gaza.jpg')}}" style="display: block;
        margin-left: auto;
        margin-right: auto;
        width: 50%;"  />

     <p style="font-size: 25px;">
        Gaza is a Palestinian coastal city, and the largest city in the Gaza Strip is located in its north,<br> 
        at the southern tip of the eastern coast of the Mediterranean Sea. It is 78 km from the city of Jerusalem<br> 
        to the southwest. It is the center of Gaza Governorate and the largest city of the Palestinian Authority in <br>
        terms of population. The population of Gaza Governorate reached 700,000 people in 2013, making it the largest <br>
        gathering of Palestinians in Palestine. It covers an area of ​​56 km2, making it one of the most densely populated<br> 
        cities in the world.<br><br><br>

Gaza City is considered one of the most important Palestinian cities, due to the importance of its strategic location and <br>
the economic and urban importance of the city, in addition to being the temporary headquarters of the Palestinian National <br>
Authority, and the presence of many of its headquarters and ministry in it.<br>
    </p>
    <div class="previous"  style="background-color:  #919292;
    top:80px;
    color: white;
    align-items: right;
    font-size: 25px;
    margin-left: 70%;
    margin: 10 px;
    padding: 10px;
    position:center;
    right:60%;
    float: right;">
              <a href="{{ url_for('views.home') }}">Retun </a>
              </div>
            </div>
</body>
</html>

CityProject/__pycache__/website/templates/jericho.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jericho City</title>
</head>
<body style="background-color:slategrey;">
   <h1>Jericho City</h1>
        <img src="{{url_for('static', filename='assets/img/slide/jercho.jpg')}}"  style="display: block;
        margin-left: auto;
        margin-right: auto;
        width: 50%;" />
        <p style="font-size: 25px;">The ancient city of Jericho is about a mile from the west,<br>
           and its place is known as the Abu Al-Alayk Hills, to the north of Tel Al-Sultan.<br>
           It dates back to 10,000-11,000 years. It was built of mud bricks, and around it was<br> 
           a trench 28 feet wide and 8 feet deep and carved from rock. Pottery, bronze artifacts,<br>
           bones, wooden household items, baskets and fabrics were discovered at its site. It was<br> 
           destroyed in the late Bronze Age and is the oldest city discovered so far. Jericho is considered<br> 
           the eastern gateway to Palestine. It is linked to the East Bank by a network of paved roads and is<br> 
           connected to the Jerusalem-Amman road. It is located to the north of the city of Jerusalem, 38 km away <br>
           from it, and 70 km from the city of Hebron in the south.
        </p> 
        <p style="font-size: 25px;">
            The city of Jericho is considered one of the cities of the climatic centers, due to its warm <br>
            climate in the winter and its great low below sea level. Therefore, many visitors come to it <br>
            in the winter to recover, and the urban form in the city retains the radioactive form, and many <br>
            streets branch off from the city center in all directions, and for this reason The style has important<br> 
            advantages, including the addition of land areas within the city, and this makes it retain health advantages.<br> 
            Jericho includes many monuments such as:<br>
Hisham's Palace <br>
A magnificent Arab palace built by Hisham ibn Abd al-Malik, who ruled in 105-125 AH (724-743 AD) on Khirbat al-Mafjar.<br> 
It is located north of Jericho, and east of Ain Duke in Khirbet al-Mafjar, 3 km from Jericho. in the West Bank.<br>
        </p>
      
    <div class="previous"  style="background-color:  #919292;
    top:80px;
    color: white;
    align-items: right;
    font-size: 25px;
    margin-left: 70%;
    margin: 10 px;
    padding: 10px;
    position:center;
    right:60%;
    float: right;">
              <a href="{{ url_for('views.home') }}">Retun </a>
              </div>    
</body>
</html>

CityProject/__pycache__/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
  %}
  <form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="text"
        id="email"
        name="email"
        class="form-control"
        placeholder="Enter Email"
      />
      <label for="password">Password</label>
      <input
        type="password"
        id="password"
        name="password"
        class="form-control"
        placeholder="Enter Password"
      />
      <br />
      <div align="center">
        <button class="btn btn-primary" type="submit">Login</button>
      </div>
    </div>
  </form>
  {% endblock %}

CityProject/__pycache__/website/templates/safed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Safed City</title>
    <link href="static/main.css" rel="stylesheet">
</head>
<body style="background-color:slategrey;">
    
        <h1>Safed City</h1>
        <img src="{{url_for('static', filename='assets/img/slide/safed.jpg')}}" style="display: block;
        margin-left: auto;
        margin-right: auto;
        width: 50%;"  />
        <br>
        <br>
        <p style="font-size: 25px;">
        Safed (Hebrew: צפת) is one of the historical cities of Palestine. The city is located in the Galilee region.<br> 
        Today, it is in the northern region of Israel. It is also considered one of the country's highest cities, about <br>
        900 meters above sea level. It is located 134 km north of Jerusalem, overlooking the Sea of ​​Galilee and the Beisan<br> 
        meadow to the southeast, and Mount Al-Jarmaq to the west. The area of ​​the city is 29,248 km², and it is inhabited <br>
        today by about 28,000 people - most of them are Jews, after the displacement of its Arab people in the 1948 war.<br> 
        It was mentioned in Jewish religious literature and among Roman historians, and since the sixteenth century, with <br>
        the fall of Andalusia and the expulsion of the Jews from the Iberian Peninsula, arose It has a community of Sephardic <br>
        Jews and followers of the Kabbalah in particular, which made it one of the four holy cities of Judaism at that time. <br>
        In the Ottoman era, it was the center of the Sanjak of Safad belonging to the Eyalet of Damascus, and during the period <br>
        of the British Mandate over Palestine, it was the center of the district of Safed.<br>
    </p>
    <p style="font-size: 25px;">
        During the archaeological excavations around the Citadel of Safed (The Orphan Tower), urban remains from the Iron Age and <br>
        Bronze Age burials were found. The city is not mentioned in the ancient sources, so it seems that it was a small town in <br>
        pre-Christian times. The Book of Judges mentions a Canaanite city called “Safat” (Judges 1:17), but it appears from the <br>
        description of its place that it fell in the Negev and has no connection with the contemporary city of Safed. The first <br>
        undoubted reference to the city of Safed is in the books of the historian Josephus Flavius, who mentions it as one of the <br>
        sites that fortified in preparation for the failed Jewish rebellion against the Roman Empire in the first century AD.<br>
    </p>
    <div class="previous"  style="background-color:  #919292;
    top:80px;
    color: white;
    align-items: right;
    font-size: 25px;
    margin-left: 70%;
    margin: 10 px;
    padding: 10px;
    position:center;
    right:60%;
    float: right;">
              <a href="{{ url_for('views.home') }}">Retun </a>
              </div>
</body>
</html>

CityProject/__pycache__/website/templates/signup.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
  content %}
  
  <form method="POST" >
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="text"
        id="email"
        name="email"
        class="form-control"
        placeholder="Enter Email"
      />
      <label for="username">Username</label>
      <input
        type="text"
        id="username"
        name="username"
        class="form-control"
        placeholder="Enter Username"
      />
      <label for="password1">Password</label>
      <input
        type="password"
        id="password1"
        name="password1"
        class="form-control"
        placeholder="Enter Password"
      />
      <label for="password2">Password Again</label>
      <input
        type="password"
        id="password2"
        name="password2"
        class="form-control"
        placeholder="Enter Password Again"
      />
      <br />
      <div align="center">
        <button class="btn btn-primary" type="submit">Sign Up</button>
      </div>
    </div>
  </form>
  {% endblock %}

CityProject/__pycache__/website/templates/weather.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>City Weather App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='static/main.css') }}">
</head>

<body style="background-color:slategrey;">
    <h1>Welcome to City Weather App</h1><br>
    <form action="/city" method="POST" style="text-align:center">
        <label for="city_name" style="font-size: 30px; " >City Name:</label>
        <input type="text" id="city_name" name="city_name" placeholder="Enter city name" style="height: 40px; width: 500px;">
        <br>
        <br>
        <input type="submit" style="font-size: 20px; ">
    </form>
    <div class="previous" style="background-color: #919292;
    top:80px;
    color: white;
    align-items: right;
    font-size: 25px;
    margin-left: 70%;
    margin: 10 px;
    padding: 10px;
    position:center;
    right:60%;
    float: right;" >
              <a href="{{ url_for('views.home') }}">Retun </a>
              </div>
</body>

CityProject/__pycache__/website/templates/yafa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jaffa City</title>
</head>
<body style="background-color:slategrey;">
    <h1>Jaffa City</h1>
    <img src="{{url_for('static', filename='assets/img/slide/jaffa.jpg')}}" style="display: block;
    margin-left: auto;
    margin-right: auto;
    width: 50%;"  /><br><br>
    <p style="font-size: 25px;">Jaffa (Hebrew: יָפוֹ Yafu) is one of the oldest and most important historical cities in Palestine.<br> 
       Today it is located within the Israeli municipality of "Tel Aviv - Jaffa", on the eastern coast of <br>
       the Mediterranean Sea - according to the Israeli administrative division. It is 55 km from Jerusalem <br>
       to the west. For a long time, it occupied an important position among the major Palestinian cities in <br>
       terms of area, population and strategic location, until the date of the Nakba in 1948, and the displacement <br>
       of most of its Arab residents. Today, it is inhabited by approximately 60,000 people, most of whom are Jews,<br> 
       and an Arab minority of Muslims and Christians.
    </p><br> 
   <p style="font-size: 25px;">
    The city was founded by the Canaanites in the fourth millennium BC, and since that date it has been an important <br>
    commercial center for the region. The Assyrian, Babylonian and Persian rule BC, and its link with the Greek <br>
    civilization was close, then it entered the rule of the Romans and the Byzantines, and its inhabitants were among<br> 
    the first to embrace Christianity. One of the most important events that the city witnessed was when the Prophet <br>
    Yunus descended on its shores in the eighth century B.C. to board a ship from it, destined for Tarshish. When the <br>
    Islamic conquest entered Palestine, Amr Ibn Al-Aas conquered Jaffa in the same year that Omar Ibn Al-Khattab entered<br> 
    Jerusalem. Jaffa continued to occupy this important position among the cities of Palestine, and remained a major <br>
    commercial center, a port for Jerusalem and a port for pilgrims. During the Ottoman period, specifically in 1885,<br> 
    the first municipal council was established in Jaffa.<br>
   </p>

   <div class="previous"  style="background-color:  #919292;
   top:80px;
   color: white;
   align-items: right;
   font-size: 25px;
   margin-left: 70%;
   margin: 10 px;
   padding: 10px;
   position:center;
   right:60%;
   float: right;">
             <a href="{{ url_for('views.home') }}">Retun </a>
             </div> 
</body>
</html>